
# List of CPP File #
LOCAL_SRC_FILES := main.cpp
LOCAL_SRC_FILES += $(CLASS_PATH)/AndroidCode/AndroidHelper.cpp
LOCAL_SRC_FILES += $(CLASS_PATH)/AppDelegate.cpp
LOCAL_SRC_FILES += $(CLASS_PATH)/HelloWorldScene.cpp
LOCAL_SRC_FILES += $(CLASS_PATH)/Helper/AdmobHelper.cpp
LOCAL_SRC_FILES += $(CLASS_PATH)/SimpleTDD/SampleTest.cpp
LOCAL_SRC_FILES += $(CLASS_PATH)/SimpleTDD/TDDData.cpp
LOCAL_SRC_FILES += $(CLASS_PATH)/SimpleTDD/TDDHelper.cpp
LOCAL_SRC_FILES += $(CLASS_PATH)/SimpleTDD/TDDMenu.cpp
LOCAL_SRC_FILES += $(CLASS_PATH)/SimpleTDD/TDDMenuTest.cpp
LOCAL_SRC_FILES += $(CLASS_PATH)/SimpleTDD/TDDSample.cpp
LOCAL_SRC_FILES += $(CLASS_PATH)/SimpleTDD/TDDSubMenu.cpp
LOCAL_SRC_FILES += $(CLASS_PATH)/SimpleTDD/TDDSuite.cpp
LOCAL_SRC_FILES += $(CLASS_PATH)/SimpleTDD/TDDSwitch.cpp
LOCAL_SRC_FILES += $(CLASS_PATH)/SimpleTDD/TDDTest.cpp
LOCAL_SRC_FILES += $(CLASS_PATH)/UnitTest/AdmobTest.cpp
LOCAL_SRC_FILES += $(CLASS_PATH)/UnitTest/AndroidTest.cpp
LOCAL_SRC_FILES += $(CLASS_PATH)/UnitTest/GATest.cpp
LOCAL_SRC_FILES += $(CLASS_PATH)/UnitTest/iOSTest.cpp


#Include DIR #
LOCAL_C_INCLUDES := $(LOCAL_PATH)/$(CLASS_PATH)
LOCAL_C_INCLUDES += $(LOCAL_PATH)/$(CLASS_PATH)/libs
LOCAL_C_INCLUDES += $(LOCAL_PATH)/$(CLASS_PATH)/AndroidCode
LOCAL_C_INCLUDES += $(LOCAL_PATH)/$(CLASS_PATH)/Helper
LOCAL_C_INCLUDES += $(LOCAL_PATH)/$(CLASS_PATH)/SimpleTDD
LOCAL_C_INCLUDES += $(LOCAL_PATH)/$(CLASS_PATH)/UnitTest
LOCAL_C_INCLUDES += $(LOCAL_PATH)/$(CLASS_PATH)/iOSCode
